use $(input);
SET NOCOUNT ON;

Insert into Skill values ('IT Operations Management');
Insert into Skill values ('Amazon Relational Database Service (RDS)');
Insert into Skill values ('Oracle WebLogic Server');
Insert into Skill values ('IBM WebSphere Message Queuing');
Insert into Skill values ('Systems Engineering');
Insert into Skill values ('Windows 7');
Insert into Skill values ('Java EE');
Insert into Skill values ('Spanish');
Insert into Skill values ('sql');
Insert into Skill values ('windows');
Insert into Skill values ('English');
Insert into Skill values ('MS Excel');
Insert into Skill values ('Linux');
Insert into Skill values ('PowerPoint');
Insert into Skill values ('PL/SQL Developer');
Insert into Skill values ('ServiceNow');
Insert into Skill values ('Requirements organization');
Insert into Skill values ('Information Technology Infrastructure Library (ITIL)');
Insert into Skill values ('English');
Insert into Skill values ('Unix');
Insert into Skill values ('Windows 10');
Insert into Skill values ('Office 365');
Insert into Skill values ('Confluence');
Insert into Skill values ('Office equipment usage');
Insert into Skill values ('Apache Tomcat');
Insert into Skill values ('Information Technology Infrastructure Library (ITIL)');
Insert into Skill values ('Oracle WebLogic Server');
Insert into Skill values ('Apache HTTP Server');
Insert into Skill values ('IBM WebSphere Commerce');
Insert into Skill values ('MS Excel');
Insert into Skill values ('Windows Installer');
Insert into Skill values ('PuTTY');
Insert into Skill values ('selenium');
Insert into Skill values ('sql');
Insert into Skill values ('Business correspondence');
Insert into Skill values ('Linux');
Insert into Skill values ('Bash');
Insert into Skill values ('Conflict solving');
Insert into Skill values ('Windows Server 2012 (R2)');
Insert into Skill values ('DBMS Engineering');
Insert into Skill values ('Root Cause Analysis');
Insert into Skill values ('ITIL Operational Support and Analysis');
Insert into Skill values ('HP Service Manager');
Insert into Skill values ('MCITP: Windows Server 2008');
Insert into Skill values ('IBM Softlayer');
Insert into Skill values ('SSH');
Insert into Skill values ('MS Word');
Insert into Skill values ('Apache Commons');
Insert into Skill values ('Project Management');
Insert into Skill values ('JBoss');
Insert into Skill values ('MS Outlook');
Insert into Skill values ('ITIL (ServiceNow)');
Insert into Skill values ('Visual Studio Code');
Insert into Skill values ('Systems Engineering');
Insert into Skill values ('junit');
Insert into Skill values ('oracle');
Insert into Skill values ('Phone conversation etiquette');
Insert into Skill values ('JIRA');
Insert into Skill values ('ServiceNow');
Insert into Skill values ('Windows Server 2008 (R2)');
Insert into Skill values ('Bash');
Insert into Skill values ('Unix');
Insert into Skill values ('Problem Tracking');
Insert into Skill values ('Windows Server 2012 (R2)');
Insert into Skill values ('SAP Hybris Commerce');
Insert into Skill values ('Server Administrator');
Insert into Skill values ('IBM WebSphere');
Insert into Skill values ('T-SQL');
Insert into Skill values ('log4j 2');
Insert into Skill values ('IT Service Management (ITSM)');
Insert into Skill values ('Spring Core');
Insert into Skill values ('SSH');
Insert into Skill values ('Networking');
Insert into Skill values ('Bootstrap');
Insert into Skill values ('HP Network Node Manager');
Insert into Skill values ('design patterns');
Insert into Skill values ('MS Word');
Insert into Skill values ('UNIX shell scripting');
Insert into Skill values ('OpenOffice');
Insert into Skill values ('PL/SQL');
Insert into Skill values ('VMware vSphere');
Insert into Skill values ('MySQL');
Insert into Skill values ('WordPress');
Insert into Skill values ('Messaging & Communications');
Insert into Skill values ('Engineering design');
Insert into Skill values ('FI');
Insert into Skill values ('XML/XSL/XSLT');
Insert into Skill values ('Windows 8');
Insert into Skill values ('Eclipse IDE');
Insert into Skill values ('Data (Evidence');
Insert into Skill values ('Amazon Elastic Compute Cloud (EC2)');
Insert into Skill values ('Hitachi Vantara Pentaho Data Integration (Data.ETLPlatform)');
Insert into Skill values ('HP Operations Manager for Unix');
Insert into Skill values ('c#');
Insert into Skill values ('vmware workstation');
Insert into Skill values ('Oracle VirtualBox');
Insert into Skill values ('MS Windows');
Insert into Skill values ('Call management (Call Center)');
Insert into Skill values ('DB2 UDB');
Insert into Skill values ('NFS');
Insert into Skill values ('Windows');
Insert into Skill values ('Writing Technical Documentation (English)');
Insert into Skill values ('DB2 for LUW');
Insert into Skill values ('Writing Technical Documentation (English)');
Insert into Skill values ('Adobe Acrobat Professional');
Insert into Skill values ('Mechanical Engineering');
Insert into Skill values ('Tidal');
Insert into Skill values ('Software Maintenance');
Insert into Skill values ('IBM SmartCloud');
Insert into Skill values ('Git');
