use $(input);
SET NOCOUNT ON;

INSERT INTO COMPETENCY VALUES ('DEVOPS','Fernando Mendez')
INSERT INTO COMPETENCY VALUES ('AppSupport','Victorino Cazares')
INSERT INTO COMPETENCY VALUES ('ServiceDesk','Graciela Manzo')
INSERT INTO COMPETENCY VALUES ('Cloud','Carlos Corona')
INSERT INTO COMPETENCY VALUES ('SysOps','Martin Rodriguez')
INSERT INTO COMPETENCY VALUES ('Testing','Carlos Aleman')
INSERT INTO COMPETENCY VALUES ('SEED','Omar Arana')
INSERT INTO COMPETENCY VALUES ('Security','TBD')
