//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTSOInterviewers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public int IdPosition { get; set; }
        public string Description { get; set; }
        public string Project { get; set; }
        public byte IdCompentecy { get; set; }
        public Nullable<short> IdSkillPrimary { get; set; }
        public Nullable<short> IdSkillSecondary { get; set; }
        public Nullable<short> IdSkillOptional { get; set; }
    
        public virtual Competency Competency { get; set; }
    }
}
